---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secret
  namespace: default
spec:
  encryptedData:
    password: AgChr767FBApR+lt/LgPHtMG/ax+PBYa1jiSNtGbXc3ZTN23URMZQmKOuBpjH/f8m4zT4WXNhaQix99kGl/fFfrU37424ltxWxo+M06lfrAG8pbGwWVm6yHHCxrO5zMQUXGyNXzUT8EgHUwqBPVkKBjGOByuAdAWfdK2krehoEtnnGY/ACrUKrHsAL8AQLBjtd+KsoDjnA9K8i5/C1p1Ze4+12jzhKaC5cglrmDYl8p/Of03QFPJyf0VH9T9VfM8qLdkOSUF2tslydXkFLFGm0OyWiA8NrvJ1JecTeuocDnZzYqMZfaqhtzSJ1vxkYt2R1LLDXvWyUYOBitAVW8FEpe348EIf9u9d6xq7esSHhS28ca7Y5MvDv6D8uM6U12vZWik6PcFGivd/RL1rd20YMgWWoqLHEgLgr1npk0LoQgkCsnA8lD0SFZJVJjOj92qhuvTxnG2WjKPByWB709Mo85SIexZmwVdeJDldC2yRJY8RYJ+mt8XEU5tbPbK+RPBx8b8a5FB4ADR5DU2GBc4qjKwj8WF4DENG27jQjujf5CQv2aN/ifTYxuQlLbBoFda8PwQWsvitgpVTpefgZTSAti7pNDVjVdb56IAnNzGW9TGiOvm3ooRf8vj7i74PokzN5nfCQwDIdJTHK8sknddcNcmxdlNPJ8gkMfKbyTr0ob5vrqgXg5NADkehwyZhpXoAMOMSRtsUK8ax7kzQcL5hhzK5/dEdC+DADw=
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secret
      namespace: default
