---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: general
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: general
  resources:
    requests:
      storage: 10Gi
