apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: general
  resources:
    requests:
      storage: 100Gi
