---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-rcon-secret
  namespace: minecraft
spec:
  encryptedData:
    rcon-password: AgBOzF0ZyachMXhUfaB87RFHtT/J5gviGcc79jRxfqMa1V+S2VmXYJAWRrsTXLhdvWGmzkiFk2Jzt/K3KiLMRif8lNLtAt22vdGDsPEyvdf5z1EDo/0jkQ76c9qu77ZYs6FyB3cvU+Iv44Y4K/ADManx5C7w5Of7ADcy4lfDVRxCveVghudikv3J02n2wZeI+7XQQlbBk5fQaFmyFIudFRc6OOtmhUsstBKIGtz3kT/R2j3Q8wgO74/JwuS0TtqCc2MPhmGWkuBz6OdwpVKHFmIc1cnxbritdnmthdXf+N+WG9XZbGRjAYoirmj5KhZFxRVFWR2YqaDmEw5U6NwfvkBDbOAwrjCcXhaDvTmgNL6mCamWam9G5fFNJxAtmE6ZUtyd2gRi41xFrgAWB+itPJTYUFtK+6+35zOC1wZJZEnsYH24IN5abQha8ACoqhuP6Jp9A0LeVRiUNJwSb9wwRy+9ORh78yzLBUz23ZC+dHOP0AN9H1cmxJDXQ2mBHSQ4+Q/W52otk+gZBCWrZ539sYV7XfwbU7T0kN4/yaJD1jAE2oufQfquqo3uylld2cVLIEbAfBNNYyiSpKhz5HqFe25Wu6VEyviQFrLqXhyzBCb+k+WbRBRautc2mR0wg8br7CHwjYFIa8qf5PqhOm5WutQfwD8hlcevUya6hP78Fm6tL5tVdKUBvUXmqAIjj0vwFqkZIQAa4bIdWXMTIVEtSai064DeXJzfiWoTlf5R/Q==
  template:
    metadata:
      name: minecraft-rcon-secret
      namespace: minecraft
