apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "8.*"
    helm:
      releaseName: argo-cd
      valuesObject:
        global:
          domain: "argo.tail.{{ .Values.ingress.baseDomain }}"
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
        configs:
          params:
            server.insecure: true
          secret:
            createSecret: false
        server:
          ingress:
            enabled: true
            ingressClassName: nginx-tailnet
            annotations:
              cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer.tailnet }}
            extraTls:
              - hosts:
                - "argo.tail.{{ .Values.ingress.baseDomain }}"
                secretName: argo-cd-tls
  destination:
    server: "{{ .Values.destination.server }}"
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
