apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argo-cd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "cert-manager-{{ `{{ name }}` }}"
      namespace: argo-cd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        chart: cert-manager
        repoURL: https://charts.jetstack.io
        targetRevision: "1.13.*"
        helm:
          releaseName: cert-manager
          valuesObject:
            installCRDs: true
            nodeSelector:
              node-role.kubernetes.io/control-plane: "true"
            webhook:
              nodeSelector:
                node-role.kubernetes.io/control-plane: "true"
            cainjector:
              nodeSelector:
                node-role.kubernetes.io/control-plane: "true"
      destination:
        server: "{{ `{{ server }}` }}"
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: false
          allowEmpty: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
