apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-resources
  namespace: argo-cd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: cert-manager-resources-{{ "{{ name }}" }}
      namespace: argo-cd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/younishd/infra
        targetRevision: master
        path: apps/cert-manager-resources
      destination:
        server: {{ "{{ server }}" }}
        namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
