apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-resources
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/younishd/infra
    targetRevision: master
    path: apps/cert-manager-resources
    helm:
      releaseName: cert-manager-resources
      valuesObject:
        spec:
          email: {{ .Values.spec.certManager.email }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
