apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  generators:
    - matrix:
        generators:
          - clusters: {}
          - list:
              elements:
                - scope: public
                  http: "80"
                  https: "443"
                - scope: tailnet
                  http: "8880"
                  https: "4443"
  template:
    metadata:
      name: "ingress-nginx-{{ `{{ name }}-{{ scope }}` }}"
      namespace: argo-cd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        chart: ingress-nginx
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: "4.8.*"
        helm:
          releaseName: "ingress-nginx-{{ `{{ scope }}` }}"
          valuesObject:
            controller:
              service:
                type: "NodePort"
                nodePorts:
                  http: "{{ `{{ http }}` }}"
                  https: "{{ `{{ https }}` }}"
              ingressClassResource:
                name: "nginx-{{ `{{ scope }}` }}"
              ingressClass: "nginx-{{ `{{ scope }}` }}"
              nodeSelector:
                node-role.kubernetes.io/control-plane: "true"
      destination:
        server: "{{ `{{ server }}` }}"
        namespace: "ingress-nginx-{{ `{{ scope }}` }}"
      syncPolicy:
        automated:
          prune: true
          allowEmpty: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
