apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: ingress-nginx-{{ "{{ name }}" }}
      namespace: argo-cd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        chart: ingress-nginx
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: "4.8.*"
        helm:
          releaseName: ingress-nginx
          valuesObject:
            controller:
              service:
                type: "NodePort"
                nodePorts:
                  http: 80
                  https: 443
              nodeSelector:
                node-role.kubernetes.io/control-plane: "true"
      destination:
        server: {{ "{{ server }}" }}
        namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
