apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-path-provisioner
  namespace: argo-cd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "local-path-provisioner-{{ `{{ name }}` }}"
      namespace: argo-cd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/rancher/local-path-provisioner.git
        targetRevision: HEAD
        path: deploy/chart/local-path-provisioner
        helm:
          releaseName: local-path-provisioner
          valuesObject:
            storageClass:
              reclaimPolicy: Retain
              nodePathMap:
                - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
                  paths:
                    - /data
      destination:
        server: "{{ `{{ server }}` }}"
        namespace: local-path-storage
      syncPolicy:
        automated:
          prune: false
          allowEmpty: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
