apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mastodon
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mastodon/chart
    targetRevision: HEAD
    path: "."
    helm:
      releaseName: mastodon
      values: |
        {{- tpl (.Files.Get "config/mastodon.yaml") . | nindent 8 }}
  destination:
    name: ovh-cluster
    namespace: mastodon
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
