apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mastodon
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: mastodon
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "4.7.1"
    helm:
      releaseName: mastodon
      values: |
        {{- tpl (.Files.Get "config/mastodon.yaml") . | nindent 8 }}
  destination:
    server: "{{ .Values.destination.server }}"
    namespace: mastodon
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
