apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-resources
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/younishd/infra
    targetRevision: master
    path: apps/nextcloud-resources
  destination:
    name: ovh-cluster
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
