apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ovh-cluster-secret
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/younishd/infra
    targetRevision: master
    path: apps/ovh-cluster-secret
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
