apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-resources
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/younishd/infra
    targetRevision: master
    path: apps/plex-resources
  destination:
    server: ovh-cluster
    namespace: plex
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
