apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: plex-media-server
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    targetRevision: "0.1.8"
    helm:
      releaseName: plex
      valueFiles:
        - config/plex.yaml
  destination:
    name: ovh-cluster
    namespace: plex
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
