apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-resources
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.source.repoURL }}"
    targetRevision: "{{ .Values.source.targetRevision }}"
    path: apps/plex-resources
  destination:
    server: "{{ .Values.destination.server }}"
    namespace: plex
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
