apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: sealed-secrets-{{ `{{ name }}` }}
      namespace: argo-cd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        chart: sealed-secrets
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: "2.13.*"
        helm:
          releaseName: sealed-secrets
          valuesObject:
            nodeSelector:
              node-role.kubernetes.io/control-plane: "true"
            keyrenewperiod: 0
      destination:
        server: "{{ `{{ server }}` }}"
        namespace: kube-system
      syncPolicy:
        automated:
          prune: false
          allowEmpty: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
