apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission-resources
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/younishd/infra
    targetRevision: master
    path: apps/transmission-resources
  destination:
    name: ovh-cluster
    namespace: plex
  syncPolicy:
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
