- name: Gather information
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Gather facts from first control plane node
      ansible.builtin.setup:
      delegate_to: '{{ groups["control_plane"][0] }}'
- name: Roll out RKE2 on first control plane node
  hosts: control_plane[0]
  become: true
  gather_facts: true
  any_errors_fatal: true
  tags: rke2
  tasks:
    - name: Install and start RKE2
      ansible.builtin.import_role:
        name: rke2

- name: Install RKE2 on all remaining nodes
  hosts: control_plane[1:]:data_plane
  become: true
  gather_facts: true
  any_errors_fatal: true
  tags: rke2
  tasks:
    - name: Install RKE2
      ansible.builtin.import_role:
        name: rke2
        tasks_from: install

- name: Start up remaining RKE2 control plane nodes one by one
  hosts: control_plane[1:]
  become: true
  gather_facts: true
  any_errors_fatal: true
  tags: rke2
  serial: 1
  tasks:
    - name: Start RKE2
      ansible.builtin.import_role:
        name: rke2
        tasks_from: start

- name: Start up RKE2 data plane in parallel
  hosts: data_plane
  become: true
  gather_facts: true
  any_errors_fatal: true
  tags: rke2
  tasks:
    - name: Start RKE2
      ansible.builtin.import_role:
        name: rke2
        tasks_from: start
