apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app.kubernetes.io/name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transmission
    spec:
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:4.0.5
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: config
              mountPath: /config
          {{- if .Values.persistence.enabled }}
            - name: downloads
              mountPath: /downloads
          {{- end }}
          env:
          - name: USER
            value: admin
          - name: PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.existingSecret }}
                key: password
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: transmission-config-volume
      {{- if .Values.persistence.enabled }}
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- end }}
