apiVersion: v1
kind: Service
metadata:
  name: transmission-peer-svc
spec:
  selector:
    app.kubernetes.io/name: transmission
  type: NodePort
  ports:
    - protocol: TCP
      port: 30413
      targetPort: 30413
      nodePort: 30413
    - protocol: UDP
      port: 30413
      targetPort: 30413
      nodePort: 30413
