---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mastodon-redis
  namespace: mastodon
spec:
  encryptedData:
    password: AgCcpr3YzFyEqbtEavK9xdDSYshCMBjkpWDOw8WhF7oQaMIrgQPiNPOTBR7IE+4agv5/L1Et7qXG/5x/klFYYSu1yWzWX3hmBMGfsbKvfJXsNezHueTlYP4XH26+QKQDIHt6HQW1xvclG8bDbZdr+AytLz0f6rgkOvVAqoecDdO+gFjfBjT49b4SVi9/fS8FYN/1SniZ+NItozk4x2uCSoGem5Huf/VLf+7cCw1tmN3P6lW2/uVbNtNk+Mif2/aid4P800N92DpzxN1GhUjwELu2ow5lHF4tWxcN1MUmqQNfJjULkqbHrOcGsLMmwARCWb5jRGhu3xtbmEtxZx3f81TwHK8N7DNaTYV3XdNWWeCd6H00C6KuRkgOBaqTTgeHr+hOKIWJG8WYnVZbzZz1oEemWycbELl+88R9F+g+7/hcB2778UPgB9VmI+hG1Rw/ewQFRUcoUDnOTumA3hqv16+BJGgCe7D44snod57jaiw/bsrDdlVB5yGXWHDPlBFsbiNRm62g/WZr3+NGpmioSb8d5kQBQ2HvfX4jsFhHWU29mauRJcPtC4y0V2vfy+x8WN3RpBwQaflaDutF2sFNoJBSUTDcJyVVLoUI+F3XG96qsviE8cl3I0C8UeWbZD+NqgkAq9exQAKUawsEanvayAEQPslIOMlOKLrxMN7GfYaaqqfuNVYwYHjwXLjphO0X1W358NPJ8li2gAbMfIdzu85CoHkUbQ/EaBQrf4DeqpJ7OQ==
  template:
    metadata:
      creationTimestamp: null
      name: mastodon-redis
      namespace: mastodon
