---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth
  namespace: mastodon
spec:
  encryptedData:
    redis-password: AgBgrDrx2z4LG08olhXQdE3YXVuFlr72yuUGjn0G/1ocxGlDxSccV67yO05xrnI3l90upl/th4zveOk5/Ow04Sgjh2qwj/cNzbZYe7G47t93jpnuGce/ZIrh124A3xef7StFMEBe7n4NY2ZibXjMeZpD0gCr7jSH6i1YIa+I09+yXwfwo8LsFqk0rgdbC4cmXfZPuC+VbR8xlLzuC1vg/DASo7VxepFVTYwYSXGeCqRjeIygKJtCS3gOYzkqtfUbBuVMJ8SMF8Dw9yJSxuXRhq/4PQyqKvf71r3rOAK8Rd864jQ5O5RmwYDzQySNszOeD03e9Cdt+3ggt7k8HxyG6M68CfwlYK/Dj4Ia9EPfQKxRc7Rq5tQ9LvFC4lCH73l11fM5N8smrD96x2rLJ/q6bGOzqrePKqFn8msKdY81/7fCeX41m+gHz5U4P1xgV1ZAt2EKyUHqfi6+RLH7rc1ahNFTR0UfJblffl10XWKyWW36v1DRJ1meJDK1nDoeBHQlPZDyr6gYAfpkY4dZGRlZXkYiFROREOMQN/eAFYnflYkOsBV3M3N+RGufvryrpcx3W4hPRDtqCdcLBDNq4TCmY8soUdmcRla+h2HOll8E+jSE6r5PEUGXDaQXmil2tPxrIOpBdGomLJJzTUEgPpUb3U6pAfywHH+4UCPQ8cE59r6+xp9Fn8lZ48jkzT45fShV1rq2llN3M+IyJ5xca2ZstpWIRSN1cfKLEzg=
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth
      namespace: mastodon
