---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mastodon-smtp
  namespace: mastodon
spec:
  encryptedData:
    login: AgChKfAaUmfUPEekkoIPEhYCcMH+lX1Ujk1HEdhHRYCAvC3fhJbfMHLuh71KmLWvMGNU7/njPUFMJ4EAhCMZ7dji9cejGt7tW/Fxvyw8so0DoaIafaYEx/08xHa1khWOdguqFZIW60/ASS7djE6x3U0BkSXNkBpxbk0s+GDbAzsrf7p6rmvpV9cf4G3USoEtIzj9mQnzovkK5+iDhL13JdEmXeJQYhS6qgAygZSTX3t2Jfylbui/bccG0BZhLxcz7HpKgzdLDH5yHaSbN6lncPKLFS6ZvO0F75nE/586IforB+m8ZyAyLtDVO+zyAqIwBxnM0LHTqdg0r++pMytnNIj8UFFGj3d7bMt3if2Go1YETcpAjKIr3PYeV6hMns5DXtNH0vCKMVXvejiOpA439rjjeZH9dRNjv3XqJyOCoXMsDPzdlzEDd0ppO7ijw9+9VRT4gQB/pufCU+DecHEIW/V7NYjOcZ86wUX/Vr/JaeLDF7ROIEXZa7Pj4/ih261tst4j9uFU0EUUp715yAIAl0Sza2e4Ptsl/SE2exZLe6vpg+GE/RokV+HIw67fn7bHlqjwHsD3CHbvcIgsSoaiBFqSZMHz6N93MIglD96FPvqcosamESfUrqnRaOkjkI7S8iVB2LbvslLQ4rTywjRcKEAbPIjLoTEf7NzhnnERu0+xbX//64HVz7+bCtb8e7zNWcD0WDvpBRGgzx9iatq/iYQtqafeWbMbYvW7
    password: AgBqE6kEwJIXJKGtN7qyzVkhQ+3+R6YqtQTFG8hC4rVIbfE6L+305ZCdYk8y+fQO+QtdTRnZzx+NbrjslVWHGGlGSxm8NCFSeJ/fEu49MUQGGncMZJmn7jzHjvz4gi0YqbkTDoJVoiYQ/gJsRk9JFU8xf5it2Tr9gnyikDY49kFykNOvrPPH8/vdtLN0VBjApDSj8g1KBYfQQYuodBfcwz1Zk+70sik+AgfQmVBOsF7eZDlq4pkO6VSzdoJOCo2SJ8F6ZiOvJTj9xKWZyrUJgwXci9Fmf9aVKo7bkBgySFrnGsmfijdHbsmADKPixp9rWHi2Oc00j7LnAk3XCAqLAfYbO8YmA+BDI0KUt0NU0cxAa4hFeYSAonPBdcf3KhU3cUZAGoEw+Q4iUhWMDmKGZ/T0f7pWqlHAHoXcnst4cBN5AXnN02bfmM4cHodH18fz+kU1+XzpYWFiA6VMnzI9IAi1fcsCsDPDcacj5pQ00+Vwju0T+jCdLLsrJA2FgMUqfHNVVxsf8zp0VNkE7Q1OqGAzTEzqJDtq6SUTBJrmtEM5yKnysYmMks8OkAknshObwgfmw1KHCx8vGPrGCbeMQI4KVyfvrqF4tt+1g1H8saXQSnjJsfIyX0H103ZccE6KMBbyEdkXarQ1JQ47r3SVeOfoYLpg55xPrXwMvLhOr/6XaC//6ob4ka6qBxW87gv8Skb3NmyYO9V1fGiq9vzyy2Y5
  template:
    metadata:
      creationTimestamp: null
      name: mastodon-smtp
      namespace: mastodon
