apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-resources
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.source.repoURL }}"
    targetRevision: "{{ .Values.source.targetRevision }}"
    path: clusters/home/apps/cilium-resources
  destination:
    server: "{{ .Values.destination.server }}"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
      selfHeal: true
