apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: "2.*"
    helm:
      releaseName: sealed-secrets
      valuesObject:
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
  destination:
    server: "{{ .Values.destination.server }}"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
