ingress:
  enabled: true
  ingressClassName: nginx-public
  url: "plex.{{ .Values.ingress.baseDomain }}"
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer.public }}
  tls:
    - hosts:
        - "plex.{{ .Values.ingress.baseDomain }}"
      secretName: plex-tls

pms:
  storageClassName: local-path
  configStorage: 10Gi # has no effect

extraVolumeMounts:
  - name: plex-volume
    mountPath: /data

extraVolumes:
  - name: plex-volume
    persistentVolumeClaim:
      claimName: plex
      readOnly: true

service:
  type: NodePort
  nodePort: 32000
