minecraftServer:
  eula: "true"
  version: "1.20.5"
  type: "PAPER"
  difficulty: "hard"
  whitelist: "neoprene,nileane"
  ops: "neoprene"
  maxPlayers: 16
  maxWorldSize: 1000000
  spawnProtection: 0
  viewDistance: 16
  levelSeed: "192421863"
  gameMode: survival
  motd: '\u00a7bDivision\u00a7a\u00f7\u00a7eIsland'
  memory: 3072M
  overrideServerProperties: true
  serviceType: NodePort
  nodePort: 30000

persistence:
  dataDir:
    enabled: true
    Size: 64Gi
    accessModes:
      - ReadWriteOnce
