minecraftServer:
  eula: "true"
  version: "1.21.3"
  type: "PAPER"
  difficulty: "hard"
  whitelist: "neoprene,nileane"
  ops: ""
  maxPlayers: 16
  maxWorldSize: 1000000
  spawnProtection: 0
  viewDistance: 16
  levelSeed: "192421863"
  gameMode: survival
  motd: '\u00a7bDivision\u00a7a\u00f7\u00a7eIsland'
  memory: 4096M
  overrideServerProperties: true
  serviceType: NodePort
  nodePort: 30000
  rcon:
    enabled: true
    withGeneratedPassword: false
    port: 25575
    existingSecret: minecraft-rcon-secret
    secretKey: rcon-password

mcbackup:
  enabled: true
  backupInterval: 24h
  pruneBackupsDays: 7
  backupMethod: tar
  destDir: /backups

persistence:
  dataDir:
    enabled: true
    Size: 64Gi
    accessModes:
      - ReadWriteOnce
