nextcloud:
  host: "cloud.dev.{{ .Values.spec.baseDomain }}"
  existingSecret:
    enabled: true
    secretName: nextcloud-auth
    usernameKey: username
    passwordKey: password
  configs:
    trusted.config.php: |-
      <?php
      $CONFIG = [
        'trusted_domains' => ['cloud.dev.{{ .Values.spec.baseDomain }}']
      ];

nodeSelector:
  kubernetes.io/hostname: savanna-plateau

ingress:
  enabled: true
  className: nginx-public
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    cert-manager.io/cluster-issuer: {{ .Values.spec.clusterIssuer.public }}
  tls:
    - secretName: nextcloud-tls
      hosts:
        - "cloud.dev.{{ .Values.spec.baseDomain }}"

persistence:
  enabled: true
  existingClaim: nextcloud-volume

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: mysql
  existingSecret:
    enabled: true
    secretName: mariadb-auth
    databaseKey: mariadb-database
    usernameKey: mariadb-username
    passwordKey: mariadb-password
    hostKey: mariadb-host

mariadb:
  enabled: true
  auth:
    username: nextcloud
    database: nextcloud
    existingSecret: mariadb-auth
  primary:
    nodeSelector:
      kubernetes.io/hostname: savanna-plateau
    persistence:
      enabled: true
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 10Gi

cronjob:
  enabled: true
