ingress:
  enabled: true
  ingressClassName: "nginx"
  url: "plex.dev.{{ .Values.spec.baseDomain }}"
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.spec.clusterIssuer }}

pms:
  storageClassName: local-path
  configStorage: 10Gi

nodeSelector:
  kubernetes.io/hostname: "savanna-plateau"

extraVolumeMounts:
  - name: some-volume-name
    mountPath: /video

extraVolumes:
  - name: some-volume-name
    persistentVolumeClaim:
      claimName: plex-volume
      readOnly: true
