ingress:
  enabled: true
  ingressClassName: "nginx"
  url: "plex.dev.{{ .Values.spec.baseDomain }}"
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.spec.clusterIssuer }}

pms:
  storageClassName: local-path
  configStorage: 10Gi

service:
  type: NodePort
  port: 32400

nodeSelector:
  kubernetes.io/hostname: "savanna-plateau"
