ingress:
  enabled: true
  ingressClassName: nginx-tailnet
  hostname: "tx.tail.{{ .Values.spec.baseDomain }}"
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer.tailnet }}

persistence:
  enabled: true
  existingClaim: plex

existingSecret: transmission-secret
