ingress:
  enabled: true
  ingressClassName: nginx-tailnet
  hostname: "tx.tail.dev.{{ .Values.spec.baseDomain }}"
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.spec.clusterIssuer.tailnet }}

persistence:
  enabled: true
  existingClaim: plex-volume

existingSecret: transmission-secret
