---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCC6iBZiqcZS0se+GsYh2U3xo4wribJjKvgOib2z7dS7bn3SanXm5qjQJCZATePFu6bcdgAOVION476VTCMmzJtxOT4+o01n24YvGlw5OK3xXth9RMgO69XRplp8XPVxIaXPM0HcwtguScK+A5ig2sDcgpu7q9Eox3zqp7W9a0JtWZnaDI34HH8JDvmM4i9Bzc1iSuYeRHBeRHH1mBVfP0FHT/MFDN+McCl5BZzyPp6A2BkkBESQSKUzAO9+V4jNxsdSWZj1Q69tQqy86lxnPd89HQNe5r4gMDR+UZyRdVce0K+OB6M7QziPyn/fsTOKhdcN6l/fNJ/cS4/KkQv5jF/5siKc1pPHZdPBiqDVceTvRmwuJvzT2/x/LV5J4ZfePEO93cK+Yv8AWKu7VgDVtfNYz5g8rF/wPvAkA+FOzv2YlqEd5OUTDkhbGJXdzf5a1kqg8oxEp7eCbFmNBhqhf6TCJPPvA3gmvGc/DBRbJMzB/RK45QgtLRPlVD4hG8tVBfQ6fhYfuGWXfrcOjn9R/qlKDLgNa0gFge1OsegVolpuWrfPPzCpjtUFK1hGMRaX6vIL47YOq7tff6eRtzjekBkfX0TsXKajWwcx+4vKojw1B29YqtP/BHVoRHIevTCQB/VW2YHiEHhghrIToBxI1oaSMypPDdg1XIKvVXuK1hLsD7kgq7Sz1BxHjEiORhE4DbYnwhsUrSAHWR//jn9qpa3ss+iIjQjeowC83UKFsscALbuC0jmFq1D
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
