---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCJjoN4HOvd/bueNmneD2hl3kJxfl7nFE0HizfzpuYYMrVldwjPxBefo0XWBJzcgCh4LQwhFifGctETkaZWQz9NuYtFNUkT/hWZGuuRBD8Yyd3zV+vFJd6rlzrcF+FnWItBG9UZ4ilvvtMa0M9t/gd0roMEBJZWvz4BgktFX84HBaD9HSdDJyplJxbQ75jrafG+9L1D6n+yNIXUdQRxkt+XaBrFLjLnhfunTHxS7WDWOcG2K/D+BWfiBdccOzrtxmdW07Ym20ujy6nSuLfJmZ1NM98HN9C3fB8IftBE2tQCqTbqq99fEsk0eVw9ul79XyHnBdVFzUmud7XxW53daPYYa2O/aUeYsKQziet3IeItEEuxsxOsDG6y2m7Y4L2AgJrUOoJ2dcdOtOgDFaZnaAcGfGDrOUHue19+IKJNcPTBmnsAiqC2Sm1qs22nF/H34ck+S5rxcDk5aI1qgz0+qMtFA1UB0UJ8mOxvthqVXSlNJgU6VubpOIS3HqqgKxF7P5idTVMhTR/rW1+1ad3JcyxektC7n+7BQcVx9Yj4sC4p4gMlk+xMq1xSRO/R7rtFRUw3e3hby1nmuMPpKPGHP2G1cAQcuivwbyGkAImnpEwG1r0y9EOb6v6TtG3GIzxPl3CRjObnulE2bki0zQi0VBL1HrlBl+7IEGjTjEjFIa+CMqsFgMavzBbFXha0ex0WbsSQ/FgG3aRUAGo6mdY1ZcibWW/WUjG77YXqcSYJ8i5A/6eAskQHhMnV
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
