---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA+1dho7ES2trGJHVZoye/Yuv5aZeq9m2S+2943ZMLxiZvT4I9t112TV32PKk8mJvLfWxlETHN2dyOWAVXrXZA0XTGFKLTR5MT4E17kANXUZO5CYXsS8f8njDAX7ri7kAxuroOQyIcKyZiqXtXo1MaWjTXlyIjIc7hKGzqefW1CNuxhTrqHqdY6dHCn1Ae5pqEfiY/XY5efTZBQzEEc7X4+i7FArLNWzEjYyopPtHIwIqXUfTMalI69bgx1nbKdzI+2wUjs9s1tD3nmIRdm2YTL1rwv5gX99lyUjcDKvJCwFmMAYrAM5oXu+QrCDWn3yGiy7Qeh02g34h6JELPIFspu1kweusvlgs3zcHTyY/BQ/FncR978Ff0XmRLGPxTZHzTOsUywu4+EoRnOhG6388DR96FOZ3GVU+aKljzE0Ym/7vVc60SkJnzWf9jeBYYFyNPpSbzHnDj5LCKfZ3yoN1pJandiAKwUOeYOpRWIDXOC/RlceZM+WL6b4qifWy/4YxFwYng1Wp+Q8bvqGI/Afc3FjQzjT4xzFMeyl+uDS8ATR2LcQMKvPb1YuAj9aZhv4l+c32WLWXV7PSeZ30SsiFp3aHwkZ8CVnQMQbV0RabLm4cDuI7ofRpWonwFzwPwecKEquv3VfZ7TCOS7qDXe4o3PDc1rUSefJXCrYkID4e9KruGJRU7rGPkgF3jjipOmRVRPZBgROKFV4FqwxMHIeB/ZPX00OkS7aJmDgEiTX34Jklxc2Fdb/nOj
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
