---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCJ1pQT054bDHsNf3KnOGPlfj28OydYMUkFrdI5oC7oDDi0+KivnAx7Jz9AwvHFGoH3vIb10NDwYpr91WNFGoyQ3KXAJ9mL8D+gNeWNCLlrmzQrU5qlUWjamwxeAAZt1D+iShcDA9bytGtwq+6p7ePCq8v5mSVYeakrjYAHqlWPGZ0MtcjcltLINZvRjPhvWVxv7Sg+y6jWPylbsekTgjeaKWE2lU4VWrw5WwmXkYi6xm24+sF0YOPLmpwNgAauzXbVEKoV8AHvbEOQXrlAejAsjrHmMXgK3odRLTx1wFmU/Ze99DTei8fnuH+KYGhoBfD0TvT36CBFhx3uLadJTJnAZTg+l+xcHmLQXWLG4NUmhBzEDhiEAeFNPXiuvP0jLEruPiUpFumN532G8sEFL7NVpWbOGZarl0bXhkKZDR6NjpI2JZ7e/MaBVOEG3rOsAukM4qKwt1+hH0biXXwCUvXyUPHOBAJjouzTZiS7td9HZS/d6JRHi+22kSvNywk/hSiHUiiKKDIo9eX0rAhlLiutmj+Vbke48yakCHcYdAVSkKul/d9iXc9hKTqcTDqnlVHVi3p7Y4TI95Kmz9P0YI2kPmNsTF+94r6OhHwt9JJrK69Wnlk3K1khtTd4GQ7ozSR+a3c6J/lhorAmP/L1imHNoxJzePzfS0feUO4+6tc7AHhXIC/gBOACCOg73yIUBB2TF80Yv9IljTa3TWwGr35Ut4XhSAx3/xiq/wVOWIsIq4S52bespBZO
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
