---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gandi-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCivR7PcxbHozyLPPpI8cHsx8DlJZSDBOPHtK4L3niG2rxT31LoXtg8d23M+OQShnRiB4iI+ofZAvI6wnhJdOhCSyjggbealaJqcoFs5b8fPDwYB5CwpjY202KzTxTovMQqzFEQ+2a3Ozcq+m8fkkeqNK3LCuGNVB5c1v+Mumv/ZPazZwVetrekLsbSdNwwA7wE5mkYgGsyBmMGZAe/M43tF3fboPQXn7esrVE99/FqBA556j+yZ8LrrkaRznNCVOVv158S5ORs8SOV56y5iTm9/MnsCNMosxx2an47maBTRd9OuwddhEAFL+8vRx9pfXQJblfPiJxf1l+IDrq1V04yh/7kxlRA6iDwgje320RrDx31JNp5IKXIoyThZgzi/Qpz/FhrHk+//km75L89QM/38j8SANe3Jxrc26QTumEf1IEvcci5JzkwnYimfVPrMZLIIMkgwkBICAcE4k61HaVqdADZ63rxQ+ZtvsCrNjNHQ4bXFeTmfrDhYGUNPXE5MtPG+Te9i+DRq1bKXyRcGIEVvvPSUSVpsDVB2NQmgmmPeae6bxA0wXv13aA5EMeDh9A+wjm12BW/O9d6xWYLYWvKSnf7FvZB1K0WaDz92eOoxhtejclECjSvaZCZl0rwkfqwj/s4D6AMSpb7ps2QWqa0fQjipULbFIAgXqEkRJa2Ad1vrYG27W02W1o2mmD48Lei8gOveUdkYMf6BBwn0ZKc5o+F/ZdJSp0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gandi-credentials
      namespace: cert-manager
    type: Opaque
---
