- name: Enable IPv4 forwarding in kernel
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-ip-forward.conf

- name: Install iptables-persistent
  ansible.builtin.apt:
    pkg:
      - iptables-persistent
    update_cache: true
    cache_valid_time: 3600

- name: Flush all NAT rules
  ansible.builtin.iptables:
    table: nat
    flush: true

- name: Masquerade outgoing packets
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ uplink_iface }}"
    source: "{{ private_cidr_ipv4 }}"
    jump: MASQUERADE

- name: Save iptables NAT rules to file
  ansible.builtin.command:
    cmd: "iptables-save -t nat -f /etc/iptables/rules.v4"
  changed_when: true

- name: Enable and start netfilter-persistent service
  ansible.builtin.systemd:
    name: netfilter-persistent
    enabled: true
    state: started
