installCRDs: true
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
webhook:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
cainjector:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
