deployment:
  kind: Deployment
  replicas: 2

ports:
  web:
    nodePort: 30080

  websecure:
    nodePort: 30443

ingressClass:
  enabled: true
  isDefaultClass: true

service:
  spec:
    type: NodePort
    externalTrafficPolicy: Local
