deployment:
  kind: DaemonSet
  dnsPolicy: ClusterFirstWithHostNet

hostNetwork: true

nodeSelector:
  node-role.kubernetes.io/tailscale: "true"

ports:
  web:
    port: 80
    exposedPort: 80
  websecure:
    port: 443
    exposedPort: 443

ingressClass:
  enabled: true
  isDefaultClass: true

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
