---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAuI+1OP9SKFYUDG8fuBQoZ/WY0vXuaNZ2dtYK+q3iwglchJ+P3wuRUrmDtJcCZXsXVoFBfGe7//nw6KoYDvOdVeH+nwfcVLgFYIFXH0F31FKecAqIrzSskznsfKPg8UwhnwH1MaQdTq2McU5ecOCv53SJBNHguAvVN8uCZ3h/f3vzesLN12OScZjgivgBajDcemJSb48XVqDL2ykoObVT9+WJghMrBS7mC5IFk12oHXyBZDZrtcwBnoug0fqY0c3g4Pm652owW/w9Re4OxuQsQLeWeS+uiO45qemgik/9iNtbuWLgcF2H4TPxUmd9FenDSgUoxeihoy4lCgso/4/KsdGs7xiErWfeP8MSy3fxXFNTtwARZt2hzXlGjdhnTtqpsc9iIofIAFM3IrtJiUlR17bILUn+SQshWiU2A27Dgp8Dh/wocSkukIJ+JgTV2agTjRNlNfU+8h7f/ugrD+TiNgeb/N/Lcr80+VmdorkFS6TXA3wBWq7DyKrOxyTOOajHhUQx2l3uetUX4Apq6iYkii4AEKUg+fSbNMBy6xE5NwXk9SBYKiXX8Od4cPoG0Mg4wZbBlsNqrGpWyjPvmuVhZVmMe8Qp+xnpgwc2Z35XSMTk9/5bZb4s2QioDkceAORHjf6wDV8nNap98389ONIMQq3WmBKmLI9x7/odBR9IXNcSRqPyYOP/J738ZR/fYEl6CF1yGdRgl/ABSN1bdksoZou8qZ+EiveCGdNN7Kb+9UchuH7jZPIsn
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
