---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAiIgpqDJvzDotwFswVy40vGbqhjZ8wR+anJMkI/+zBMcsWOBe+SlJZWBZARcMLg2CZtn1XWZFj5ovgyMgSEMlXnKOvCCajX7j6tDD9JCWP2/H4vMpkc93klphOUbeZcId5glHd+zhFomvldJdwmRqbLXZkDRpRM9SUJCXtVHxdj11cybdIVrmXgEQg1xJY1Z0LaJ1KYVj+GaAahe/MwGXKZ4T4c47JYtpJPivAtuKWk/2Zjosd3/+9dYFTePjgRBANwv58Owsu7y4ue1/4RPH4TFDppiSbGgySCvUt9pgxd3+z8y/ByTWm8CcqzuyzwA4OjFx7jkWZYqGvHBHkIXLqNLwyu26DXOWLLisM3WX+qUAKXuoFIMWQoGOf3QD33HHKuUriKXB8etxbWBfvvMC1YVGFiqobkLf60gDo6ScV/aIqGfF9UIfzczriN9be88MDqA+Xtb1g/efFpdFOZZdN9Pt6wSpJKtN3JK8IwPr/ZLMLOkIAcW3Wur4S5hj0HLhhVk3K8NING1rTcC1lCqs6uKcE8WG+yPtY6LaAwFMt2YE9qWJkSfhCXPq1kVZfmmmzvZu9rb8MvV2YUQsMwIvFzL8JyJs5tqjLg5ZP2dc/nPHev7TMZG3WU9PX9Hf04/igt/ks6w69FSJnItdnFU2B1IC35Vq6XP5V9HA1+X0Hn3pMvYXSaEJbr+SDVhS3hgvaH2cOvbj0GCMOA7PioCzUr3nuOS+gq0IJtE3TxvDpYkDSwrxAgNN7
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
