---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgArjpzNCIz6n4NbNzGNsA1C+um990SRemDl+Y7TWbR8diCBU5GLKn3aXws8hTuSZO4FtBO6E3BNHnpFb/nh5FzVfOPyvQkdPsQ3s2KFSec5yCcdqD/VPkhMnShH50nBrCwsUAfFGG5nnZ3QVqZL6WFZYxEZ958BEtWNOmycAqrTWJHYwLAY1NeJnj3TZFVuCyHjODXORxQHxmC4WuwRvHWTD+thcIS//dc1nztk3zgY7QmRjZybhX6wloFJSjo9rJPHdIwKjFRvf36AASDFzO359fpHuskXYRcCRkeWr0OenVhry5hDnCCFE+ZtEKTghXrD6r0XJ2LURtDMOX3a9LC36XNr0DRc0Y4bkYRagjskXr4Ik9MlAYtj6t3+sReRnpLy3Owsg3qBjcPWjCeWq3yHG7UPnIQ6xikjQMBz13SGdUt1X6ptQqAgfjAMoJKqTAEUXt5x/5B8A2gEdmFbgfmEPWUwh92Uc6N6pxGLBppYZ1oi9b9kRJltmqv5HmvcFUNGpf0iYr1Lrqlft2RchnLSfjAASiGpOudnMiqzRJoRhqsu/OyNKNig/xXq7Ct0zQyXuljkecuXD1kPwT1NiB6wlAHoVJ6138wsDTEd51V9R2ZAWWX499RVkj0J498bZWGHffW3mPEE8NIjhXoxbkG8Z77W6wZVsPrk1U2SWOIPVs3XOe5OY8ZbBbP42ADafN95B9AaiN91/++1ZspmDh6JieX0jK3ybjRtmda6aROS+i6sE9TXcqVj
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
