ansible_ssh_common_args: "-F ssh/ovh.config"

argocd_enabled: false

node_labels:
  control_plane:
    node-role.kubernetes.io/control-plane: "true"
  data_plane:
    node-role.kubernetes.io/data-plane: "true"

cluster_cidr_ipv4: "10.62.0.0/16"
service_cidr_ipv4: "10.63.0.0/16"
